.TH GALAXY 1
.SH NAME
galaxy, mkgalaxy \- galactic n-body simulator
.SH SYNOPSIS
.B galaxy
[
.B -i
]
.br
.B mkgalaxy
[
.I options
] [
.B -i
]
[
.I size
]
.SH DESCRIPTION
.I Galaxy
is an n-body simulator that uses a Barnes-Hut quad-tree
to calculate gravitational interactions.
Typical usage is to read in the output from mkgalaxy (see
below) using the
.B -i
command-line option.
If
.B -i
is not given then the simulator starts with an empty
universe.
.SS Mouse commands
.PP
Mouse button 1 creates a new galactic body. Holding button
2 at the same time as button 1 changes the size/mass of the body.
Holding button 3 while holding button 1 changes the initial
velocity of the body. Releasing button 1 restarts the simulator
with the new body in motion.
.PP
Holding mouse button 2 while dragging up or down zooms the
visible region of the galaxy in or out, respectively.
Holding mouse button 3 while dragging repositions the
visible region of the galaxy.
.SS Keyboard commands
The following keys are recognized as commands:
.TP
.B q
Exit the simulator.
.TP
.B space
Pause and unpause the simulator.
.SS Mkgalaxy
.I Mkgalaxy
is a utility to create galaxies for simulation.
Galaxies can be assembled incrementally by reading an
existing galaxy file from standard input with the
.B -i
command-line option or from a
.I file
with the
.B -f
option. Mkgalaxy then writes to standard output a
.IR galaxy (6)
file with a galaxy of the given
.I size
together with the previously read galaxy.
Galaxies generated by mkgalaxy have characteristics
determined by the following options:
.TP
.BI -d " distance"
.I Distance
determines the spacing between bodies.
The default value is 100.
.TP
.BI -sz " size"
Bodies have the given
.IR size .
The default value is 25.
.TP
.BI -v " velocity"
Bodies have the given
.I velocity
in a random direction.
The default value is 0.
.TP
.BI -av " angular velocity"
Bodies have the given
.I "angular velocity"
relative to the center of mass of the new galaxy being generated.
The default value is 0.
.TP
.BI -gv " x,y"
The entire galaxy being generated is given the directional velocity determined
by the vector
.RI ( x,y ).
The default value is (0, 0).
.TP
.BI -o " x,y"
The entire galaxy being generated is offset by the vector
.RI ( x,y ).
The default value is (0, 0).
.TP
.B -sq
The galaxy being generated is a square. Without this option, the galaxy
will be circular.
.PP
The arguments to the
.BR -d ,
.BR -s ,
.BR -v ,
and
.B -av
arguments have the form
.B s
or
.B s+r
where s and r are double-precision floating point numbers.
.B S
is the base value and
.B r
if given determines a range in which the value will vary randomly
from the base.
.SH EXAMPLES
Two rotating circles destroy each other:
.IP
.EX
mkgalaxy -av 100 -d 60+50 -v 10 2000 |
mkgalaxy -i -av=-70 -d 80+50 -v 10 -o 6000,2000 -gv=-80,40 3000 |
galaxy -i
.EE
.PP
Cool patterns made by a square galaxy:
.IP
.EX
mkgalaxy -sq -av 20 5000 | galaxy -i
.EE
.SH SOURCE
.B https://github.com/spewspews/galaxy
.SH SEE ALSO
J. Barnes & P. Hut (December 1986). "A hierarchical O(N log N) force-calculation algorithm".
.IR Nature .
324 (4): 446–449.
.PP
.IR galaxy (6)
.SH HISTORY
.I Galaxy
and
.I mkgalaxy
first appeared in 9front (Feb, 2017).
